//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDGameSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aparencia
    {
        public int idAparencia { get; set; }
        public decimal Peso { get; set; }
        public decimal Altura { get; set; }
        public string CorCabelo { get; set; }
        public string EstiloCabelo { get; set; }
        public string CorOlho { get; set; }
        public string CorPele { get; set; }
    }
}
