//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDGameSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atributo
    {
        public int idAtributo { get; set; }
        public int Forca { get; set; }
        public int Destreza { get; set; }
        public int Sabedoria { get; set; }
        public int Constituicao { get; set; }
        public int Inteligencia { get; set; }
        public int Carisma { get; set; }
    }
}
