//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDGameSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personagem
    {
        public int idPersonagem { get; set; }
        public string Nome { get; set; }
        public int Nivel { get; set; }
        public string Sexo { get; set; }
        public int idRaca { get; set; }
        public int idSubclasse { get; set; }
        public int idAtributo { get; set; }
        public int idAparencia { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
    
        public virtual Aparencia Aparencias { get; set; }
        public virtual Atributo Atributos { get; set; }
        public virtual Raca Racas { get; set; }
        public virtual Subclasse Subclasses { get; set; }
    }
}
