//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDGameSolution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subclasse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subclasse()
        {
            this.Personagens = new HashSet<Personagem>();
        }
    
        public int idSubclasse { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> idClasse { get; set; }
    
        public virtual Classe Classes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personagem> Personagens { get; set; }
    }
}
