CREATE TABLE Aparencias(
	idAparencia INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Peso DECIMAL (12,2) NOT NULL,
	Altura DECIMAL (12,2) NOT NULL,
	CorCabelo VARCHAR (255) NOT NULL,
	EstiloCabelo VARCHAR (255) NOT NULL,
	CorOlho VARCHAR (255) NOT NULL,
	CorPele VARCHAR (255) NOT NULL,
);